version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: examen_mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: examen_db
    ports:
      - "27017:27017"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d

  mongo-express:
    image: mongo-express:1.0.0-alpha
    container_name: examen_mongo_express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongodb
    depends_on:
      - mongodb
